package com.auth.AuthService.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;

@Builder
@DynamoDBTable(tableName = "Users")
public class UserData {
    private String id;
    private String login;
    private String email;
    private String password;

    public UserData() {
    }

    public UserData(String id, String login, String email, String password) {
        this.id = id;
        this.login = login;
        this.email = email;
        this.password = password;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "login")
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @DynamoDBAttribute
    @DynamoDBRangeKey(attributeName = "email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "password")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
