package com.auth.AuthService.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;

@DynamoDBTable(tableName = "Tokens")
public class VerificationToken {
    public static final int EXPIRATION = 60 * 24;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Long Id;

    @DynamoDBAttribute
    @DynamoDBRangeKey(attributeName = "email")
    private String token;

    @DynamoDBAttribute(attributeName = "UUID")
    private String userUUID;

    @DynamoDBAttribute(attributeName = "expiryDate")
    private Date expiryDate;

    public Long getId() {
        return Id;
    }

    public void setId(Long id) {
        Id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUserUUID() {
        return userUUID;
    }

    public void setUserUUID(String userUUID) {
        this.userUUID = userUUID;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    private Date calculateExpiryDate(int expTime) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Timestamp(calendar.getTime().getTime()));
        calendar.add(Calendar.MINUTE, expTime);
        return new Date(calendar.getTime().getTime());
    }
}
